# Generated by Django 3.0.4 on 2020-03-16 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_time', models.DateTimeField()),
                ('comment', models.TextField()),
                ('interview_type', django_fsm.FSMField(choices=[('shortlist', 'Short Listed'), ('technical', 'For Technical Round'), ('practical', 'For Practical Round'), ('hr', 'For HR Round')], default='shortlist', max_length=50)),
                ('tag', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Candidate')),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr', to=settings.AUTH_USER_MODEL)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
