# Generated by Django 3.0.4 on 2020-03-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='interview_type',
        ),
    ]
