# Generated by Django 3.0.4 on 2020-03-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20200324_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='interview_type',
            field=models.CharField(choices=[('technical', 'For Technical Round'), ('practical', 'For Practical Round'), ('hr', 'For HR Round')], default='technical', max_length=50),
            preserve_default=False,
        ),
    ]
