# Generated by Django 3.0.4 on 2020-03-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_schedule_interview_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
