# Generated by Django 3.0.4 on 2020-03-26 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_evaluation'),
        ('scheduler', '0003_schedule_interview_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='interview_type',
            field=models.CharField(choices=[('technical', 'Technical Round'), ('practical', 'Practical Round'), ('hr', 'HR Round')], max_length=50),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_tag', models.CharField(choices=[('not_specified', 'Not Specified'), ('unsatisfactory', 'Unsatisfactory'), ('satisfactory', 'satisfactory'), ('average', 'Average'), ('above_average', 'Above Average'), ('exceptional', 'Exceptional')], default='not_specified', max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Questions')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Schedule')),
            ],
        ),
    ]
