# Generated by Django 3.0.4 on 2020-03-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20200316_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='tag',
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('not_specify', 'Not Specify'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='not_specify', max_length=50),
        ),
    ]
