# Generated by Django 3.0.4 on 2020-03-16 09:31

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='Status',
            field=django_fsm.FSMField(choices=[('shortlist', 'Short Listed'), ('technical', 'For Technical Round'), ('practical', 'For Practical Round'), ('hr', 'For HR Round')], default='shortlist', max_length=50),
        ),
    ]
