# Generated by Django 3.0.4 on 2020-03-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='question_tag',
            field=models.CharField(choices=[('not_specified', 'Not Specified'), ('unsatisfactory', 'Unsatisfactory'), ('satisfactory', 'satisfactory'), ('average', 'Average'), ('above_average', 'Above Average'), ('exceptional', 'Exceptional')], default='not_specified', max_length=50),
        ),
    ]
