# Generated by Django 3.0.4 on 2020-03-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_candidate_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='Status',
            new_name='status',
        ),
    ]
