# Generated by Django 3.0.4 on 2020-03-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200317_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='token',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
