# Generated by Django 3.0.4 on 2020-03-16 09:41

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200316_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=django_fsm.FSMField(choices=[('shortlist', 'Short Listed'), ('technical', 'For Technical Round'), ('practical', 'For Practical Round'), ('hr', 'For HR Round'), ('rejected', 'Rejected')], default='shortlist', max_length=50),
        ),
    ]
