# Generated by Django 3.0.4 on 2020-03-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200318_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.CharField(choices=[('2', '0 - 1'), ('1 - 2', '1 - 2'), ('2 - 3', '2 - 3'), ('3 - Above', '3 - Above')], default='0 - 1', max_length=20),
        ),
    ]
